name: CI/CD for AWS Cloud

on:
#  pull_request
#  schedule:
#    - cron:  '5 0 * * *' # UTC 00:05 AM - 5 minutes after DB update daily
  
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Docker Image for Development Environment
        run: docker build -t nishkarshraj/covid19 .

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
        
      - name: Docker Push
        run: docker push nishkarshraj/covid19
      
      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform plan
        run: terraform plan
      
      - name: Terraform apply
        run: terraform apply -auto-approve
      
      - name: Terraform destroy
        run: terraform destroy -auto-approve
